---
##################################
## defaults answer config     ##
##################################


# global cluster config
network_dns: "172.31.31.99"
network_gateway: "172.31.31.99"


# server specific config
server_hostname: 'node01.example.com'
server_address: '"172.31.31.199/24'
