---
########################################
## CUST-MIA1-TESTNODE1 - DELL R640    ##
########################################

# global cluster config
network_dns: "172.31.31.99"
network_gateway: "172.31.31.99"
network_domain: "livewiretech.internal"

# local config
server_hostname: "pve-node4"
server_address: "172.31.31.21/24"

